{
  lib,
  dockerTools,
  runCommand,
  writeShellApplication,
  microsandbox,
  jq,
}:

{
  name,
  contents ? null,
  image ? null,
  config ? { },
}:

let
  cmd = config.cmd or [ "/bin/sh" ];

  imageConfig = {
    Cmd = cmd;
  }
  // lib.optionalAttrs (config ? env) {
    Env = lib.mapAttrsToList (k: v: "${k}=${v}") config.env;
  }
  // lib.optionalAttrs (config ? user) { User = config.user; }
  // lib.optionalAttrs (config ? workdir) { WorkingDir = config.workdir; };

  effectiveImage =
    if image != null && contents != null then
      throw "microsandboxTools.buildSandbox: pass either `image` or `contents`, not both"
    else if image != null then
      image
    else if contents != null then
      dockerTools.buildLayeredImage {
        inherit name contents;
        tag = "latest";
        config = imageConfig;
      }
    else
      throw "microsandboxTools.buildSandbox: must pass either `image` or `contents`";

  rootfs =
    runCommand "${name}-rootfs"
      {
        nativeBuildInputs = [ jq ];
      }
      ''
        mkdir -p $out
        work=$(mktemp -d)
        tar -xzf ${effectiveImage} -C "$work"
        for layer in $(jq -r '.[0].Layers[]' "$work/manifest.json"); do
          # Pre-create every directory entry so they exist with umask
          # permissions (0755). Some image producers (notably
          # dockerTools.buildImage) ship directories with mode 0555,
          # which would block tar from writing files into them.
          tar -tf "$work/$layer" | awk '/\/$/' | (cd $out && xargs -r -I{} mkdir -p -- "{}")
          tar -xf "$work/$layer" --no-overwrite-dir -C $out
        done

        mkdir -p $out/etc
        [ -f $out/etc/passwd ] || echo 'root:x:0:0:root:/root:/bin/sh' > $out/etc/passwd
        [ -f $out/etc/group ]  || echo 'root:x:0:' > $out/etc/group
        [ -f $out/etc/os-release ] || cat > $out/etc/os-release <<EOF
        NAME="${name}"
        ID=nix-msb
        EOF
      '';

  netFlags =
    let
      net = config.net or null;
    in
    if net == "none" then
      [ "--no-net" ]
    else if net == null || net == "public" || net == "any" then
      [ ]
    else
      throw "nix-msb: unsupported config.net value: ${toString net} (use \"none\" | \"public\" | \"any\")";

  resourceFlags =
    lib.optionals (config ? cpus) [
      "--cpus"
      (toString config.cpus)
    ]
    ++ lib.optionals (config ? memory) [
      "--memory"
      config.memory
    ]
    ++ lib.optionals (config ? user) [
      "--user"
      config.user
    ]
    ++ lib.optionals (config ? workdir) [
      "--workdir"
      config.workdir
    ];

  envFlags = lib.concatMap (kv: [
    "--env"
    "${kv.name}=${kv.value}"
  ]) (lib.mapAttrsToList lib.nameValuePair (config.env or { }));

  portFlags = lib.concatMap (p: [
    "--port"
    p
  ]) (config.ports or [ ]);

  msbArgs = lib.concatStringsSep " " (
    map lib.escapeShellArg (netFlags ++ resourceFlags ++ envFlags ++ portFlags)
  );

  cmdArgs = lib.concatStringsSep " " (map lib.escapeShellArg cmd);

  launch = writeShellApplication {
    name = "${name}-launch";
    runtimeInputs = [ microsandbox ];
    text = ''
      tmpdir=$(mktemp -d -t msb-${name}-XXXXXX)
      trap 'rm -rf "$tmpdir"' EXIT
      cp -a ${rootfs}/. "$tmpdir"/
      chmod -R u+w "$tmpdir"
      if [ "$#" -gt 0 ]; then
        exec msb run ${msbArgs} "$tmpdir" -- "$@"
      else
        exec msb run ${msbArgs} "$tmpdir" -- ${cmdArgs}
      fi
    '';
  };

  sandboxfile = runCommand "${name}-sandboxfile" { } ''
    cat > $out <<EOF
    # Sandboxfile for ${name}
    # Generated by nix-msb. Schema rendering is not yet implemented.
    # Use ${name}-launch instead for now.
    EOF
  '';
in
{
  inherit
    rootfs
    launch
    sandboxfile
    ;
  image = effectiveImage;
}
